language: php

php:
  - 7.4.6
  
install:
  - composer install
  
addons:
  sonarcloud:
    organization: "groundservices"
    token:
      secure: "fd5bd6c7ab1580bd1a79aeeefd1806b29b8cdad0"

before_script:
  - cp .env.travis .env    
  
script:
  - php artisan key:generate
  - sonar-scanner
